### ISSUE TITLE
[FR] Ability to log every N steps, instead of epochs (metrics_update_freq)

### ISSUE THREAD

**Issue by SergiyShebotnov** [neptune-ai/neptune-detectron2#15]
From [docs](https://docs.neptune.ai/api/detectron2/):

`metrics_update_freq - "...Example: Setting it to 10 will log metrics every 10th epoch."`

This may be fine for smaller datasets, but for big datasets even 1 epoch could take 7-9 hours even on A100 GPU.

It would have been great if we could specify not only the frequency in epochs, but also in steps/iterations.

Is there a workaround for this and if not, would you consider adding this feature in the future?

**Comment by SiddhantSadangi** [comment]
Hey @SergiyShebotnov 👋 
Sorry for the delay here.

There is no concept of epochs in detectron2. As such, `metrics_update_freq` logs every N iterations, and not every N epochs. 

We will also correct the misleading docs, thanks for pointing this out 🙇
